{
 "title": "Home monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "position",
    "query": "query_result(count(temperature) by (position))"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Temperature $position",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "repeat": "position",
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(temperature{position=\"$position\"}) by (position)",
     "legendFormat": "{{position}}"
    }
   ]
  },
  {
   "title": "Current Temperature $position",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(temperature{position=\"$position\"}) by (position)",
     "legendFormat": "{{position}}"
    }
   ]
  },
  {
   "title": "Current Temperature $position",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(temperature{position=\"$position\"}) by (position)",
     "legendFormat": "{{position}}"
    }
   ]
  },
  {
   "title": "Current Humidity $position",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 2 },
   "repeat": "position",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(humidity{position=\"$position\"}) by (position)",
     "legendFormat": "{{position}}"
    }
   ]
  },
  {
   "title": "Current Humidity $position",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(humidity{position=\"$position\"}) by (position)",
     "legendFormat": "{{position}}"
    }
   ]
  },
  {
   "title": "Current Humidity $position",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(humidity{position=\"$position\"}) by (position)",
     "legendFormat": "{{position}}"
    }
   ]
  },
  { "title": "Metrics over time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Temperature evolution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "avg(temperature{position=~\"$position\"}) by (position)",
     "legendFormat": "{{position}}"
    },
    {
     "expr": "avg(temperature{position=~\"$position\"} offset 1d) by (position)",
     "legendFormat": "{{position}} DoD"
    }
   ]
  },
  {
   "title": "Humidity evolution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(humidity{position=~\"$position\"}) by (position)",
     "legendFormat": "{{position}}"
    },
    {
     "expr": "avg(humidity{position=~\"$position\"} offset 1d) by (position)",
     "legendFormat": "{{position}} DoD"
    }
   ]
  },
  {
   "title": "Temperature derivative evolution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "°C/h" }
   ],
   "targets": [
    {
     "expr": "deriv(temperature{position=~\"$position\"}[20m])*3600",
     "legendFormat": "{{position}}"
    },
    {
     "expr": "deriv(temperature{position=~\"$position\"}[20m] offset 1d)*3600",
     "legendFormat": "{{position}} DoD"
    }
   ]
  },
  {
   "title": "Humidity derivative evolution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "%/h" }
   ],
   "targets": [
    {
     "expr": "deriv(humidity{position=~\"$position\"}[20m])*3600",
     "legendFormat": "{{position}}"
    },
    {
     "expr": "deriv(humidity{position=~\"$position\"}[20m] offset 1d)*3600",
     "legendFormat": "{{position}} DoD"
    }
   ]
  }
 ]
}